eureka:
  client:
    service-url:
      defaultZone: http://localhost:9090/eureka/

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
        - AddResponseHeader=Access-Control-Allow-Origin, *
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedHeaders: "*"
            allowedMethods: "*"
      routes:
        - id: discovery-server
          uri: http://localhost:9090
          predicates:
              - Path=/eureka/web
          filters:
            - SetPath=/
        - id: discovery-server-static
          uri: http://localhost:9090
          predicates:
              - Path=/eureka/**
        - id: ms-auth
          uri: lb://ms-auth
          predicates:
            - Path=/api/auth/**
        - id: ms-post
          uri: lb://ms-post
          predicates:
            - Path=/api/posts/**
          filters:
            - AuthenticationFilter
        - id: ms-user-profile
          uri: lb://ms-user-profile
          predicates:
              - Path=/api/profile/**, /api/follow/**
          filters:
              - AuthenticationFilter

server:
  port: 8080

logging:
  level:
    root: info
    org:
      springframework:
        cloud:
          gateway: TRACE
    reactor:
      netty:
        http:
          client:
            HttpClient: DEBUG

paths:
  auth:
    url: http://localhost:8080/api/auth

