spring:
  data:
    mongodb:
      uri: mongodb://tokentalk:password@localhost:27017/tokentalk
  application:
    name: ms-post

eureka:
  client:
    service-url:
      defaultZone: http://localhost:9090/eureka/

server:
  port: 0
