spring:
  data:
    mongodb:
      uri: mongodb://root:example@localhost:27017/tokentalk
  application:
    name: ms-comment

eureka:
  client:
    service-url:
      defaultZone: http://localhost:9090/eureka/

server:
  port: 0
